# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b76596d7da838866d6bb8ecfc850f0b9570107d7e664e3ac059347cbc69cf24ca254667e8d1203c24c25483a27d2d62473193e4e87ac3ef2655890546629ffcf

test:
  secret_key_base: 2be6bb72e1e62922703163b110d8c3a08c9cb59aaae69a8ad209fe3f07c15c4d2c29f56c2ab8073f498fbd0147133b341b1285415bea65dd6228c73922fa1d55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
